title: URL shortener
description: URL shortener for hyd.ai
baseurl: ""
url: "https://url.hyd.ai"

collections:
  redirects:
    output: true
    permalink: /:path/

exclude:
  - README.md
  - LICENSE
  - _redirects/template.md # copy this to add a link; never published

defaults:
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirects
